version: '2'  # ou qualquer outra versão suportada pelo Docker Compose

services:
  php:
    build: .
    ports:
      - 80:80
    volumes:
      - "./:/var/www/html" 

  mysql:
    image: mysql:8.0-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste 
    ports:
      - 3306:3306